# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: harmony-solution

custom:
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: python3
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  getAction:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /action
          method: get
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - .idea/**

